#### server URL = http://localhost:3000/

#The row corresponding to the specifyed clientNumber must disappear from
#queues table, and it must appear in statistics table with today's date

PUT http://localhost:3000/API/client_served HTTP/1.1
content-type: application/json

{
    "ClientNumber": 16
}


###

GET http://localhost:3000/API/next_client HTTP/1.1
content-type: application/json

{
    "CounterID": 1
}

### ADD A CLIENT TO THE QUEUE

POST http://localhost:3000/API/queues HTTP/1.1
content-type: application/json

{
    "service": "2"
}

### GET CLIENTS ASSIGNED TO A COUNTER

GET http://localhost:3000/API/get_assigned_clients HTTP/1.1
content-type: application/json

#Response body example

[
  {
    "clientNumber": 1,
    "serviceType": "Accounts Management",
    "counterID": 2
  },
  {
    "clientNumber": 3,
    "serviceType": "Bills",
    "counterID": 1
  },
  {
    "clientNumber": 4,
    "serviceType": "Current Account Service",
    "counterID": 3
  },
  {
    "clientNumber": 14,
    "serviceType": "Bills",
    "counterID": 7
  }
]